parameters:
    secret: ThisTokenIsNotSoSecretChangeItImmediately

    # customize the full path to external executables
    # normally they are auto-detected by `which program` or auto-discovered in the configured path in
    # System Settings -> General -> Additional $PATH variable
    # but in general it's a good idea to have your programs in your $PATH environment variable (system wide)

    #opendxp_executable_composer: php /opt/vendor/bin/composer.phar
    #opendxp_executable_soffice: /opt/libreoffice/bin/soffice
    #opendxp_executable_gs: /opt/ghostscript/bin/gs
    #opendxp_executable_pdftotext: /opt/tools/pdftotext
    #opendxp_executable_xvfb-run: /opt/tools/xvfb-run
    #opendxp_executable_pngcrush: /opt/tools/pngcrush
    #opendxp_executable_zopflipng: /opt/tools/zopflipng
    #opendxp_executable_pngout: /opt/tools/pngout
    #opendxp_executable_advpng: /opt/tools/advpng
    #opendxp_executable_cjpeg: /opt/tools/cjpeg
    #opendxp_executable_jpegoptim: /opt/tools/jpegoptim
    #opendxp_executable_php: /usr/local/custom-php/bin/php
    #opendxp_executable_nice: /opt/tools/nice
    #opendxp_executable_nohup: /opt/tools/nohup
    #opendxp_executable_ffmpeg: /opt/tools/ffmpeg
    #opendxp_executable_exiftool: /opt/tools/exiftool

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

